services:
  api:
    build:
      context: backend
      target: dev
    volumes:
      - ./backend/:/app
    env_file: ./backend/.env
    restart: unless-stopped
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: mike
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - type: bind
        source: ./SCHEMA.sql
        target: /docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8000:8080"
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
