services:
  web:
    build:
      context: frontend
      target: dev
    volumes:
      - ./frontend:/app
    env_file: ./frontend/.env
    environment:
      - VIRTUAL_HOST=dev.localhost
    restart: unless-stopped
    expose: 
      - "5173"
  api:
    build:
      context: backend
      target: dev
    volumes:
      - ./backend/:/app
    env_file: ./backend/.env
    environment:
      - VIRTUAL_HOST=api.dev.localhost
    restart: unless-stopped
    expose: 
      - "8080"
  proxy:
    image: jwilder/nginx-proxy:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: mike
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      VIRTUAL_HOST: db.dev.localhost
    expose: 
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - type: bind
        source: ./SCHEMA.sql
        target: /docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
  adminer:
    image: adminer:latest
    container_name: adminer
    expose: 
      - "8080"
    environment:
      VIRTUAL_HOST: adminer.dev.localhost
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
